### Metodo GET per ottenere la lista degli utenti
GET http://localhost/5B_php_crud/index.php/users HTTP/1.1


### Metodo POST per creare un nuovo utente
POST http://localhost/5B_php_crud/index.php/users HTTP/1.1
Content-type: application/json

{
    "name": "Bruno",
    "gender": "Male",
    "email": "danielee@gmail.com",
    "gender": "Male",
    "mobile": "34567890",
    "address": "via Roma 11"
}


### Metodo PUT per aggiornare un utente
PUT http://localhost/5B_php_crud/index.php/users HTTP/1.1
Content-type: application/json

{
    "name": "Daniele",
    "gender": "Male",
    "email": "danielee@gmail.com",
    "gender": "Male",
    "mobile": "34567890",
    "address": "via Roma 11"
}


### Metodo DELETE per eliminare un utente
curl --location --request DELETE 'http://localhost/5B_php_crud/index.php/users'


### Metodo DELETE per eliminare un utente
DELETE http://localhost/5B_php_crud/index.php/users HTTP/1.1
Content-Type: application/json

{
    "id": 1
}

